length_violation_reward: 0.0
double_victim_access_reward: 0.0
victim_access_reward: 0.0
victim_miss_reward: 0.0
correct_reward: 1.0
wrong_reward: -1.0
step_reward: 0.0
no_guess_reward: -200.0

cache_state_reset: false
reset_observation: false

verbose: 0
force_victim_hit: false
flush_inst: false
allow_victim_multi_access: true
allow_empty_victim_access: false

attacker_addr_s: 4
attacker_addr_e: 7
victim_addr_s: 0
victim_addr_e: 3
reset_limit: 1

cache_configs:
  architecture:
    word_size: 1
    block_size: 1
    write_back: true
  cache_1:
    blocks: 4 
    associativity: 1
    hit_time: 1
    rep_policy: "lru"
  mem:
    hit_time: 1000 

window_size: 161  # Longer than episode_length to avoid length violation.
episode_length: 160

cyclone_collect_data: true
cyclone_malicious_trace: false

threshold: 0.5
cyclone_coeff: 100.0
