m_server_name: "m_server"
m_server_addr: "127.0.0.1:4411"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:4412"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:4413"

train_device: "cuda:0"
infer_device: "cuda:1"

num_train_rollouts: 48
num_train_workers: 24

num_eval_rollouts: 4
num_eval_workers: 2

replay_buffer_size: 131072
prefetch: 2

batch_size: 512

optimizer:
  name: "Adam"
  lr: 1e-4

learning_starts: 65536
model_push_period: 10

entropy_coeff: 0.02

num_epochs: 1000
steps_per_epoch: 3000

num_eval_episodes: 100

seed: null

table_view: false

defaults:
  - env_config: hpca_ae_exp_9_svm
  - model_config: transformer
